# Generated by Django 2.2.14 on 2021-06-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_mpesa_payments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesa_payments',
            name='user',
        ),
    ]
