# Generated by Django 2.2.14 on 2021-07-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shopinfo_vendorbusinessinfo_vendorpaymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorpaymentinfo',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
