# Generated by Django 2.2.14 on 2021-07-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210723_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='shopLicense',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
