# Generated by Django 2.2.14 on 2021-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210723_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbusinessinfo',
            name='KRAimage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendorbusinessinfo',
            name='businessDocImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendorbusinessinfo',
            name='id_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
