# Generated by Django 2.2.14 on 2021-07-23 14:07

import accounts.models
from django.db import migrations, models
import patazoneEcommerce.storageLocation.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210723_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=patazoneEcommerce.storageLocation.utils.PrivateMediaStorage(), upload_to=accounts.models.upload_image_path),
        ),
    ]
