# Generated by Django 2.2.14 on 2021-06-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20210620_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing address'), ('S', 'Shipping address')], max_length=120),
        ),
    ]
