# Generated by Django 2.2.14 on 2021-07-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20210709_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='delivery_address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
