# Generated by Django 3.2.3 on 2021-06-18 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_adress'),
        ('orders', '0002_auto_20210618_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address_final',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_final',
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='address.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='address.address'),
        ),
    ]
