# Generated by Django 2.2.14 on 2021-07-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210702_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
