# Generated by Django 2.2.14 on 2021-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
