# Generated by Django 2.2.14 on 2021-07-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('paid', 'Shipping soon'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='ordered', max_length=120),
        ),
    ]
