# Generated by Django 3.2.3 on 2021-06-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_auto_20210617_0348'),
        ('orders', '0008_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(null=True, to='carts.Cart'),
        ),
    ]
