# Generated by Django 2.2.14 on 2021-08-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerNumber',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
