# Generated by Django 3.2.3 on 2021-05-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phones', 'Phones and Tablets'), ('billing', 'Billing address'), ('shipping', 'Shipping address')], max_length=120),
        ),
    ]
