# Generated by Django 3.2.3 on 2021-05-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phones', 'Phones & Accessories'), ('electronics', 'Electronics'), ('computing', 'Computer & Tablets'), ('home', 'Home and Office'), ('academic', 'Schooling'), ('grocery', 'Grocery'), ('beauty', 'Beauty, Heath & Hair'), ('baby', 'Baby, kids & Maternity'), ('clothes', 'Cloths'), ('sports', 'Sports'), ('houseHold', 'Household Appliances'), ('automotive', 'Automotive')], max_length=120),
        ),
    ]
