# Generated by Django 3.2.3 on 2021-06-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210615_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phones & Accessories', 'Phones & Accessories'), ('Electronics', 'Electronics'), ('Computing', 'Computer & Tablets'), ('Home and Office', 'Home and Office'), ('Schooling', 'Schooling'), ('Grocery', 'Grocery'), ('Beauty, Heath & Hair', 'Beauty, Heath & Hair'), ('Baby, kids & Maternity', 'Baby, kids & Maternity'), ('Clothes', 'Cloths'), ('Sports', 'Sports'), ('Household Appliances', 'Household Appliances'), ('Automotive', 'Automotive')], default='Phones and Electronics', max_length=120),
        ),
    ]
