# Generated by Django 3.2.3 on 2021-06-17 01:26

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backImage',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green'), ('Purple', 'Purple'), ('Maroon', 'Maroon'), ('Pink', 'Pink'), ('Violet', 'Violet'), ('White', 'White'), ('Indigo', 'Indigo')], default='Black', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='sideImage',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
    ]
