# Generated by Django 2.2.14 on 2021-07-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_slideshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='free',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='user_required',
        ),
    ]
