# Generated by Django 2.2.14 on 2021-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210705_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
