# Generated by Django 2.2.14 on 2021-07-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210706_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='topsell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P', 'Phones & Accessories'), ('E', 'Electronics'), ('C', 'Computer & Tablets'), ('H', 'Home and Office'), ('S', 'Schooling'), ('G', 'Grocery'), ('B', 'Beauty, Health & Hair'), ('K', 'Baby, kids & Maternity'), ('CL', 'Cloths'), ('SP', 'Sports'), ('HA', 'Household Appliances'), ('A', 'Automotive')], default='Phones and Electronics', max_length=120),
        ),
    ]
