# Generated by Django 2.2.14 on 2021-07-08 13:57

from django.db import migrations, models
import patazoneEcommerce.storageLocation.utils
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210707_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, storage=patazoneEcommerce.storageLocation.utils.PublicMediaStorage(), upload_to=products.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=patazoneEcommerce.storageLocation.utils.PublicMediaStorage(), upload_to=products.models.upload_product_file_loc),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='file',
            field=models.FileField(storage=patazoneEcommerce.storageLocation.utils.PublicMediaStorage(), upload_to=''),
        ),
    ]
