# Generated by Django 2.2.14 on 2021-07-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210708_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='tag1',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='tag2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='tag3',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
