# Generated by Django 2.2.14 on 2021-07-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20210724_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='connectivity',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
