# Generated by Django 2.2.14 on 2021-08-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20210731_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='slide_id',
        ),
        migrations.AddField(
            model_name='slideshow',
            name='anchor_slide_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='rs_group_slide_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='rs_layer_slide_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
