# Generated by Django 2.2.14 on 2021-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20210806_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideshow',
            old_name='rs_layer_slide_id',
            new_name='rs_layer1_slide_id',
        ),
        migrations.AddField(
            model_name='slideshow',
            name='rs_layer2_slide_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='rs_layer3_slide_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='rs_layer4_slide_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
