# Generated by Django 2.2.14 on 2021-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20210806_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minorCategory',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phones & Accessories', 'Phones & Accessories'), ('Electronics', 'Electronics'), ('Computer & Tablets', 'Computer & Tablets'), ('Home and Office', 'Home and Office'), ('Schooling', 'Schooling'), ('supermarket', 'Supermarket'), ('Beauty, Health & Hair', 'Beauty, Health & Hair'), ('Baby, kids & Maternity', 'Baby, kids & Maternity'), ('Cloths', 'Cloths'), ('Sports', 'Sports'), ('Household Appliances', 'Household Appliances'), ('Automotive', 'Automotive')], default='Phones and Electronics', max_length=120),
        ),
    ]
