# Generated by Django 2.2.14 on 2021-08-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210809_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minorCategory',
            field=models.CharField(blank=True, choices=[('smart tv', 'Smart Tv'), ('led tv', 'Led Tv'), ('projector', 'Projector'), ('home theatre', 'Home Theatre'), ('sound bars', 'Sound bars'), ('speakers', 'Speakers'), ('bateries', 'Bateries'), ('cables', 'Cables'), ('power protection', 'Power protection'), ('charger', 'Charger'), ('television accessories', 'Television Accessories')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('television', 'Television'), ('home audio', 'Home audio'), ('makeup', 'Makeup'), ('oral care', 'Oral Care'), ('hair care', 'Hair Care'), ('health care', 'Health Care'), ('luxury beauty', 'Luxury Beauty'), ('personal care', 'Personal Care'), ('mobile phones', 'Mobile Phones'), ('tabulates', 'Tabulates')], max_length=120, null=True),
        ),
    ]
