# Generated by Django 2.2.14 on 2021-08-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20210809_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('television', 'Television'), ('home audio', 'Home audio'), ('home appliances', 'Home Appliances'), ('makeup', 'Makeup'), ('oral care', 'Oral Care'), ('hair care', 'Hair Care'), ('health care', 'Health Care'), ('luxury beauty', 'Luxury Beauty'), ('personal care', 'Personal Care'), ('mobile phones', 'Mobile Phones'), ('tabulates', 'Tabulates')], max_length=120, null=True),
        ),
    ]
