# Generated by Django 2.2.14 on 2021-08-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20210809_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideshow',
            old_name='anchor_slide_id',
            new_name='slide_id',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='rs_group_slide_id',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='rs_layer1_slide_id',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='rs_layer2_slide_id',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='rs_layer3_slide_id',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='rs_layer4_slide_id',
        ),
    ]
