# Generated by Django 2.2.14 on 2021-08-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20210809_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortdescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
